name: Build and test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 11, 17, 21]
        exclude:
          - os: macos-latest
            java: 8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # TODO: Temporary fix for Windows (July 2025). See error message:
      # error STL1000: Unexpected compiler version, expected Clang 19.0.0 or newer
      - name: Setup Clang 19 (Windows only)
        if: runner.os == 'Windows'
        uses: egor-tensin/setup-clang@v1
        with:
          version: 19
          platform: x64
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Build and test
        run: |
          make build
          make test
          make test-example
      # - name: Paranoid cross-build and cross-test
      #   run: |
      #     make cross-build
      #     make cross-test
      #     make cross-test-example
