name: Root build and test
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 11, 17, 21]
        exclude:
          - os: macos-latest
            java: 8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Root build and test
        run: |
          make build
          make test
          make test-example
